image: trion/ng-cli-karma:8.3.5

stages:
  - test
  - build
  - deploy

test:
  stage: test
  allow_failure: false
  before_script:
    - npm ci
  script:
    - ng lint
    - ng test --progress false --watch false
  artifacts:
    expire_in: 1 week

build:
  stage: build
  allow_failure: false
  retry: 2
  before_script:
  - npm ci
  script:
    - ng build --prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  stage: deploy
  dependencies:
  - build
  script:
    - cp -r dist/algolia public
  artifacts:
    expire_in: 1 week
    paths:
      - public
